os: linux
language: python
dist: bionic
python:
    - "2.7"
env:
    - CKAN_GIT_REPO=ckan/ckan CKANVERSION=master
    - CKAN_GIT_REPO=ckan/ckan CKANVERSION=2.8
    - CKAN_GIT_REPO=ckan/ckan CKANVERSION=2.7
    - CKAN_GIT_REPO=qld-gov-au/ckan CKAN_BRANCH=qgov-master
services:
    - redis-server
    - postgresql
addons:
    postgresql: "9.3"
install:
    - pip install -U pip wheel
    - bash bin/travis-build.bash
    - pip install coveralls
script: sh bin/travis-run.sh
after_success:
    - coveralls

stages:
  - Flake8
  - test

jobs:
  include:
    - stage: Flake8
      env: FLAKE8=True
      install:
        - pip install -U pip wheel
        - sh bin/travis-flake.sh
      script:
        -  sh bin/travis-flake-run.sh
    - stage: test
      env: CKAN_GIT_REPO=ckan/ckan CKANVERSION=master
      python: "3.6"
  allow_failures:
    - env: CKAN_GIT_REPO=ckan/ckan CKANVERSION=master
      python: "3.6"

cache: pip